	{ cpu_perc, "CPU:%2s%%", NULL },
    { separator, "┃", NULL },
    { wifi_perc, "Wifi:%3s%%", "wlp3s0"},
    { separator, "┃", NULL },
	{ battery_perc, "Bats: %2s%% ", "BAT0"},
	{ battery_state, "%s,", "BAT0"},
	{ battery_perc, "%2s%% ", "BAT1"},
	{ battery_state, "%s", "BAT1"},
    { separator, "┃", NULL },
